import React from 'react'
import styles from './styles.module.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
  }

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <div>
            <nav>About navbar</nav>
            <main className={styles.main}>{children}</main>
        </div>
    )
}
